### ISSUE TITLE
Google Download link is deactivated

### ISSUE THREAD

**Issue by axeleen** [ethman/slakh-utils#15]
Google has disallowed download for the link given by the google form.

How to get access to the dataset now ?

**Comment by ethman** [comment]
I'm sorry to hear that! Google Drive sometimes restricts access to large files if it has been downloaded too much in a 24 hour period. It looks like it's gotten a bit of traffic recently, so I think it might be best to wait.

I am also trying to get it on zenodo and hope to have that soon. I will update this issue when it is available there.

**Comment by axeleen** [comment]
Thanks for your answer :)

> Google Drive sometimes restricts access to large files if it has been downloaded too much in a 24 hour period

This is what they claim but AFAIK this error actually means they have disabled the link permanently. (It's pretty common, supposed to prevent mass CDN usage of their servers.) I've been trying for several days.

Isn't there any other temporary mean to get the dataset for now ?

**Comment by ethman** [comment]
Ack! That's extremely annoying. I think Google has been sporadically restricting access for a little bit now.

As I mentioned, I've started the process of migrating the dataset to Zenodo. When compressed, the dataset is above their default file size limit, so I am waiting on them to manually override this and allow me to upload it.

I'm hoping to have it available by the end of the week if that fits within your time frame.

**Comment by axeleen** [comment]
Thanks a lot again for your quick answers ! Having it by the end of the week would be great, but no worries, I'll wait the time it needs :).

**Comment by ethman** [comment]
Alright, give this a shot: [https://zenodo.org/record/4599666](https://zenodo.org/record/4599666)

**Comment by ethman** [comment]
Hey, just want to follow up on this. Are you able to access the dataset on zenodo?

**Comment by axeleen** [comment]
Hi there, sorry for the late reply (I was on other work). I indeed successfully downloaded the dataset thanks to the zenodo link you provided. Thanks a lot for your work.

**Comment by ethman** [comment]
Closing due to Zenodo link. Feel free to reopen if you have more issues.
