### ISSUE TITLE
Missing S00 stems in train set and validation set

### ISSUE THREAD

**Issue by KinWaiCheuk** [ethman/slakh-utils#20]
I am trying to do source separation with slakh2100, but during data processing, I realized that some tracks have S00 stem missing in the dataset.
```
train/Track00446
train/Track00487
train/Track00590
train/Track01009
validation/Track01672
validation/Track01740
validation/Track01794
```

I thought I might have downloaded a corrupted dataset, so re-downloaded the whole dataset. But those S00 stems are still missing.

**Comment by ethman** [comment]
There is more MIDI data than audio data, which means that not all of the tracks will necessarily have audio data. Does the metadata for those tracks indicate that there should be audio for S00?
