### ISSUE TITLE
resplit_slakh.py missing?

### ISSUE THREAD

**Issue by nystromer** [ethman/slakh-utils#7]
I can't seem to find the resplit_slakh.py script (mentioned in the readme) anywhere? Also can't find any alternative branches. 

Also tried `python split_slakh.py -s /home/carlnys/data/slakh/slakh2100_flac/ -n redux.json` but raises `KeyError: moved`

**Comment by ethman** [comment]
Whoops. Thanks for catching that. Looks like it wasn't committed. It's here now: https://github.com/ethman/slakh-utils/blob/master/splits/resplit_slakh.py
